version: '3.8'

services:

  exchange-events-processor:
    build:
      context: ..
      dockerfile: dev/dockerfile
    env_file: .env
    ports:
      - "8082:8080"
    restart: unless-stopped


networks:
  default:
    external: true
    name: trading